//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPosBackOffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class udt_Product
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public int CategoryId { get; set; }
        public decimal Price { get; set; }
        public int UnitType { get; set; }
    
        public virtual udt_CNV_UnitType udt_CNV_UnitType { get; set; }
        public virtual udt_ProductCategory udt_ProductCategory { get; set; }
    }
}
