//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GPosEntities : DbContext
    {
        public GPosEntities()
            : base("name=GPosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<udt_CNV_UnitType> udt_CNV_UnitType { get; set; }
        public virtual DbSet<udt_Manufacturer> udt_Manufacturer { get; set; }
        public virtual DbSet<udt_Product> udt_Product { get; set; }
        public virtual DbSet<udt_Supplier> udt_Supplier { get; set; }
    }
}
